name: multistockfish
description: "Multiple flavors of Stockfish Engine"
version: 0.0.1
repository: https://github.com/lichess-org/dart-multistockfish.git
homepage: https://github.com/lichess-org/dart-multistockfish.git

environment:
  sdk: ^3.8.0-70.0.dev
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.4
  flutter:
    sdk: flutter
  logging: ^1.3.0
  plugin_platform_interface: ^2.0.2
  stockfish_hce:
    path: pkgs/stockfish_hce
  stockfish_nnue:
    path: pkgs/stockfish_nnue

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
