name: fairy_stockfish
description: "Multi-variant Stockfish"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ^3.8.0-171.0.dev
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
