name: multistockfish_example
description: "Demonstrates how to use the multistockfish plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.0-70.0.dev

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  multistockfish:
    path: ../

  cupertino_icons: ^1.0.8
  logging: ^1.3.0
  path_provider: ^2.1.5
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
